<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

   Copyright (c) 2012 Berner Fachhochschule, Switzerland.
   Bern University of Applied Sciences, Engineering and Information Technology,
   Research Institute for Security in the Information Society, E-Voting Group,
   Biel, Switzerland.

   Project Univote.

   Distributable under GPL license.
   See terms of license at gnu.org.

-->
<definitions name="VotingService" xmlns="http://schemas.xmlsoap.org/wsdl/"
	targetNamespace="http://univote.bfh.ch/election" xmlns:tns="http://univote.bfh.ch/election"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

	<types>
		<xsd:schema>
			<xsd:import namespace="http://univote.bfh.ch/election" schemaLocation="VotingService.xsd"/>
		</xsd:schema>
	</types>

	<message name="castVote">
		<part name="parameters" element="tns:castVote"/>
	</message>
	<message name="castVoteResponse">
		<part name="parameters" element="tns:castVoteResponse"/>
	</message>
	<message name="VotingServiceFault">
		<part name="fault" element="tns:errorCode"/>
	</message>

	<portType name="Voting">
		<operation name="castVote">
			<input message="tns:castVote"/>
			<output message="tns:castVoteResponse"/>
			<fault message="tns:VotingServiceFault" name="VotingServiceFault"/>
		</operation>
	</portType>

	<binding name="VotingPortBinding" type="tns:Voting">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
		<operation name="castVote">
			<soap:operation soapAction=""/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="VotingServiceFault">
				<soap:fault name="VotingServiceFault" use="literal"/>
			</fault>
		</operation>
	</binding>

	<service name="VotingService">
		<port name="VotingPort" binding="tns:VotingPortBinding">
			<soap:address location="REPLACE_WITH_ACTUAL_URL"/>
		</port>
	</service>

</definitions>
